NXP-28260: nuxeo-platform-3d marketplace - jsf plugins packaged in bu…
nuxeo/marketplace-3d pull request #5
Opened 2019-12-06 09:22 UTC by ThierryCasanova

…ndles-jsf-ui

2019-12-06 09:39 UTC, RSalem07 commented on marketplace/src/main/assemble/assembly.xml
> +    <!-- cleanups  -->
extra space

2019-12-06 09:40 UTC, RSalem07 commented on marketplace/src/main/assemble/assembly.xml
> +</project>
add a new line at the file

2019-12-06 12:23 UTC, RSalem07 requested changes
i think it's ok, we will the review of thomas, i let some comments

2019-12-09 10:43 UTC, troger requested changes

2019-12-09 10:43 UTC, troger commented on pom.xml
> +      </dependency>
Dependency management for `nuxeo-platform-3d-core-dependencies` should not be here but in the `addons/pom.xml` like other `nuxeo-platform-3d-*` dependencies.
https://github.com/nuxeo/nuxeo/blob/10.10/addons/pom.xml#L1056

2019-12-12 13:39 UTC, RSalem07 approved these changes

2019-12-13 18:10 UTC, NourNuxeo commented on marketplace/pom.xml
> -
This is a clean up. We don't do that in HF.

2019-12-13 18:10 UTC, NourNuxeo commented on marketplace/src/main/assemble/assembly.xml
> +  </target>
Just as clean up, we don't do formats in HF.

2019-12-16 09:50 UTC, troger approved these changes

2019-12-16 16:23 UTC, merged